In [184]:
import pandas as pd

In [185]:
# infratel = pd.read_csv("C:\\Users\\abhishek\\Downloads\\aspiration.ai\\INFRATEL.csv")
# infratel = pd.read_csv("~\\Downloads\\aspiration.ai\\INFRATEL.csv")
infratel = pd.read_csv("../aspiration.ai/INFRATEL.csv")

In [186]:
infratel

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,INFRATEL,EQ,15-May-2017,374.70,375.80,375.80,368.65,372.00,371.05,371.08,761032,2.824044e+08,27740,357531,46.98
1,INFRATEL,EQ,16-May-2017,371.05,371.15,380.85,370.05,375.75,376.55,377.05,1346372,5.076459e+08,42924,677288,50.30
2,INFRATEL,EQ,17-May-2017,376.55,377.60,396.50,375.10,388.95,389.90,383.22,2268036,8.691629e+08,83975,1371275,60.46
3,INFRATEL,EQ,18-May-2017,389.90,388.40,388.85,377.00,378.55,378.90,382.60,2014628,7.707910e+08,50270,1025637,50.91
4,INFRATEL,EQ,19-May-2017,378.90,381.10,387.50,374.85,379.40,378.95,379.43,2031322,7.707525e+08,63099,1020560,50.24
5,INFRATEL,EQ,22-May-2017,378.95,383.70,389.30,376.15,388.20,387.95,385.56,2772691,1.069052e+09,73071,1228540,44.31
6,INFRATEL,EQ,23-May-2017,387.95,385.00,390.00,378.40,379.90,379.85,382.84,3811223,1.459071e+09,60957,2039492,53.51
7,INFRATEL,EQ,24-May-2017,379.85,379.85,382.00,367.20,368.45,369.00,372.49,3134390,1.167521e+09,83856,1860115,59.35
8,INFRATEL,EQ,25-May-2017,369.00,369.10,376.35,365.85,368.70,373.50,371.80,7287977,2.709680e+09,89929,6053646,83.06
9,INFRATEL,EQ,26-May-2017,373.50,370.00,377.20,366.30,369.50,369.95,371.45,1918463,7.126107e+08,43541,788763,41.11
10,INFRATEL,EQ,29-May-2017,369.95,370.00,381.40,367.70,377.10,379.35,376.57,3887542,1.463948e+09,54997,2827505,72.73
11,INFRATEL,EQ,30-May-2017,379.35,379.35,379.85,365.65,373.00,372.25,371.46,1273594,4.730920e+08,28694,420437,33.01
12,INFRATEL,EQ,31-May-2017,372.25,374.25,374.35,360.65,368.20,366.60,365.34,3613527,1.320156e+09,132010,2260332,62.55
13,INFRATEL,EQ,01-Jun-2017,366.60,370.10,379.45,369.80,377.00,376.25,375.07,2505966,9.399122e+08,50681,1369539,54.65
14,INFRATEL,EQ,02-Jun-2017,376.25,376.45,382.90,371.00,373.30,374.65,376.87,1334349,5.028735e+08,37710,496717,37.23
15,INFRATEL,EQ,05-Jun-2017,374.65,381.30,384.90,375.60,380.55,382.45,381.61,3563721,1.359942e+09,74109,1871029,52.50
16,INFRATEL,EQ,06-Jun-2017,382.45,383.00,388.90,379.80,384.70,383.15,384.02,2537956,9.746330e+08,53194,1811141,71.36
17,INFRATEL,EQ,07-Jun-2017,383.15,385.75,388.60,379.70,380.40,383.20,383.79,1610112,6.179385e+08,45025,812548,50.47
18,INFRATEL,EQ,08-Jun-2017,383.20,383.00,383.10,374.80,379.50,379.85,378.44,1107704,4.191941e+08,20214,342689,30.94
19,INFRATEL,EQ,09-Jun-2017,379.85,379.85,384.75,377.10,383.00,382.65,381.29,1545424,5.892548e+08,34955,494657,32.01
20,INFRATEL,EQ,12-Jun-2017,382.65,380.55,386.00,376.80,384.75,384.75,382.05,1660758,6.344843e+08,47895,728996,43.90
21,INFRATEL,EQ,13-Jun-2017,384.75,385.00,389.85,379.55,381.55,384.20,384.56,1863956,7.168024e+08,38488,580484,31.14
22,INFRATEL,EQ,14-Jun-2017,384.20,382.70,387.40,381.45,386.90,386.10,384.75,1317476,5.068970e+08,39782,825288,62.64
23,INFRATEL,EQ,15-Jun-2017,386.10,385.30,389.10,370.65,378.25,374.80,378.94,2369536,8.979236e+08,33682,1201629,50.71
24,INFRATEL,EQ,16-Jun-2017,374.80,374.80,384.65,373.25,375.00,375.10,379.31,2699975,1.024121e+09,53617,1350780,50.03
25,INFRATEL,EQ,19-Jun-2017,375.10,376.00,383.90,373.50,375.05,376.55,380.64,2163886,8.236665e+08,50329,1353450,62.55
26,INFRATEL,EQ,20-Jun-2017,376.55,377.15,381.50,375.70,377.75,377.10,378.48,1331396,5.039095e+08,27127,283356,21.28
27,INFRATEL,EQ,21-Jun-2017,377.10,377.50,378.10,370.50,371.05,371.70,374.03,2388975,8.935386e+08,67053,1379532,57.75
28,INFRATEL,EQ,22-Jun-2017,371.70,372.20,376.50,371.00,374.90,375.00,374.83,1120673,4.200602e+08,40145,595546,53.14
29,INFRATEL,EQ,23-Jun-2017,375.00,377.35,378.55,371.05,372.50,372.15,375.39,2156583,8.095532e+08,61112,981685,45.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,INFRATEL,EQ,27-Mar-2019,312.85,316.90,318.50,311.10,317.00,316.20,315.81,2831679,8.942635e+08,40560,1293283,45.67
465,INFRATEL,EQ,28-Mar-2019,316.20,317.45,319.65,313.45,316.00,317.10,317.08,1752675,5.557310e+08,35195,836330,47.72
466,INFRATEL,EQ,29-Mar-2019,317.10,317.50,319.15,310.85,312.60,313.40,313.64,1743099,5.467129e+08,33996,545051,31.27
467,INFRATEL,EQ,01-Apr-2019,313.40,314.95,317.60,311.50,313.85,314.25,313.85,1556091,4.883735e+08,46984,562431,36.14
468,INFRATEL,EQ,02-Apr-2019,314.25,314.45,318.10,312.15,314.05,315.00,314.97,1660087,5.228746e+08,28684,618101,37.23
469,INFRATEL,EQ,03-Apr-2019,315.00,314.50,320.00,314.15,317.00,317.25,317.10,1971729,6.252407e+08,22026,850460,43.13
470,INFRATEL,EQ,04-Apr-2019,317.25,318.50,319.75,314.70,316.20,316.65,316.76,1339901,4.244321e+08,20584,616134,45.98
471,INFRATEL,EQ,05-Apr-2019,316.65,316.65,320.00,314.40,316.60,316.80,317.07,1034427,3.279891e+08,12743,368035,35.58
472,INFRATEL,EQ,08-Apr-2019,316.80,317.95,318.70,313.70,317.20,316.10,316.36,1035460,3.275760e+08,21364,414562,40.04
473,INFRATEL,EQ,09-Apr-2019,316.10,316.10,318.50,312.50,315.05,315.20,314.88,777799,2.449096e+08,23816,271676,34.93
474,INFRATEL,EQ,10-Apr-2019,315.20,315.10,318.20,313.65,315.75,315.30,316.10,1404102,4.438390e+08,31822,775639,55.24
475,INFRATEL,EQ,11-Apr-2019,315.30,315.35,317.00,311.05,314.00,313.35,314.50,1316742,4.141204e+08,29631,625947,47.54
476,INFRATEL,EQ,12-Apr-2019,313.35,314.00,317.35,313.00,314.45,314.65,315.27,777930,2.452563e+08,29889,327314,42.07
477,INFRATEL,EQ,15-Apr-2019,314.65,314.50,316.50,307.30,309.40,308.45,311.37,1493320,4.649819e+08,26567,498381,33.37
478,INFRATEL,EQ,16-Apr-2019,308.45,310.95,316.90,309.40,312.75,312.95,314.24,2057364,6.465051e+08,44808,660367,32.10
479,INFRATEL,EQ,18-Apr-2019,312.95,312.95,314.45,303.25,306.00,307.20,306.63,2227796,6.831016e+08,27258,578932,25.99
480,INFRATEL,EQ,22-Apr-2019,307.20,306.80,310.85,295.55,299.00,299.60,302.03,1606392,4.851854e+08,22777,337306,21.00
481,INFRATEL,EQ,23-Apr-2019,299.60,301.00,303.65,292.55,298.00,294.00,296.97,1532866,4.552200e+08,28285,341382,22.27
482,INFRATEL,EQ,24-Apr-2019,294.00,297.00,303.50,291.00,301.00,301.50,298.06,2572361,7.667179e+08,37887,781457,30.38
483,INFRATEL,EQ,25-Apr-2019,301.50,287.35,298.00,265.65,272.50,270.70,278.71,24061163,6.706041e+09,180731,6077265,25.26
484,INFRATEL,EQ,26-Apr-2019,270.70,273.00,278.00,271.35,273.00,272.90,274.58,8713787,2.392621e+09,95898,3410481,39.14
485,INFRATEL,EQ,30-Apr-2019,272.90,273.70,278.90,256.50,262.55,262.55,262.97,9291803,2.443455e+09,76896,5170144,55.64
486,INFRATEL,EQ,02-May-2019,262.55,262.55,272.40,262.55,272.00,270.85,270.08,5510874,1.488349e+09,79237,2464269,44.72
487,INFRATEL,EQ,03-May-2019,270.85,272.55,278.55,272.10,273.75,274.00,275.93,4234052,1.168309e+09,61606,1434583,33.88
488,INFRATEL,EQ,06-May-2019,274.00,273.00,273.50,268.30,272.25,271.85,270.47,2351319,6.359665e+08,39964,1048140,44.58
489,INFRATEL,EQ,07-May-2019,271.85,266.90,270.80,265.75,268.00,268.00,267.98,2972102,7.964706e+08,52992,1391563,46.82
490,INFRATEL,EQ,08-May-2019,268.00,268.00,270.30,263.65,267.55,266.70,267.35,2225529,5.949861e+08,51482,1075978,48.35
491,INFRATEL,EQ,09-May-2019,266.70,266.95,269.70,261.50,268.00,267.10,263.92,3520232,9.290673e+08,56601,2051103,58.27
492,INFRATEL,EQ,10-May-2019,267.10,266.30,267.00,260.75,261.75,262.25,262.76,2270319,5.965554e+08,48630,983657,43.33
493,INFRATEL,EQ,13-May-2019,262.25,261.45,269.15,259.60,265.50,265.45,266.46,3369566,8.978471e+08,49631,1103984,32.76

In [187]:
type(infratel)

pandas.core.frame.DataFrame

In [188]:
df = infratel.copy()

In [189]:
df.isnull().sum()

Symbol                    0
Series                    0
Date                      0
Prev Close                0
Open Price                0
High Price                0
Low Price                 0
Last Price                0
Close Price               0
Average Price             0
Total Traded Quantity     0
Turnover                  0
No. of Trades             0
Deliverable Qty           0
% Dly Qt to Traded Qty    0
dtype: int64

In [190]:
df = df[df['Series'] == 'EQ']
# df.drop(df[df.Series != 'EQ'], inplace = True)

In [191]:
df

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,INFRATEL,EQ,15-May-2017,374.70,375.80,375.80,368.65,372.00,371.05,371.08,761032,2.824044e+08,27740,357531,46.98
1,INFRATEL,EQ,16-May-2017,371.05,371.15,380.85,370.05,375.75,376.55,377.05,1346372,5.076459e+08,42924,677288,50.30
2,INFRATEL,EQ,17-May-2017,376.55,377.60,396.50,375.10,388.95,389.90,383.22,2268036,8.691629e+08,83975,1371275,60.46
3,INFRATEL,EQ,18-May-2017,389.90,388.40,388.85,377.00,378.55,378.90,382.60,2014628,7.707910e+08,50270,1025637,50.91
4,INFRATEL,EQ,19-May-2017,378.90,381.10,387.50,374.85,379.40,378.95,379.43,2031322,7.707525e+08,63099,1020560,50.24
5,INFRATEL,EQ,22-May-2017,378.95,383.70,389.30,376.15,388.20,387.95,385.56,2772691,1.069052e+09,73071,1228540,44.31
6,INFRATEL,EQ,23-May-2017,387.95,385.00,390.00,378.40,379.90,379.85,382.84,3811223,1.459071e+09,60957,2039492,53.51
7,INFRATEL,EQ,24-May-2017,379.85,379.85,382.00,367.20,368.45,369.00,372.49,3134390,1.167521e+09,83856,1860115,59.35
8,INFRATEL,EQ,25-May-2017,369.00,369.10,376.35,365.85,368.70,373.50,371.80,7287977,2.709680e+09,89929,6053646,83.06
9,INFRATEL,EQ,26-May-2017,373.50,370.00,377.20,366.30,369.50,369.95,371.45,1918463,7.126107e+08,43541,788763,41.11
10,INFRATEL,EQ,29-May-2017,369.95,370.00,381.40,367.70,377.10,379.35,376.57,3887542,1.463948e+09,54997,2827505,72.73
11,INFRATEL,EQ,30-May-2017,379.35,379.35,379.85,365.65,373.00,372.25,371.46,1273594,4.730920e+08,28694,420437,33.01
12,INFRATEL,EQ,31-May-2017,372.25,374.25,374.35,360.65,368.20,366.60,365.34,3613527,1.320156e+09,132010,2260332,62.55
13,INFRATEL,EQ,01-Jun-2017,366.60,370.10,379.45,369.80,377.00,376.25,375.07,2505966,9.399122e+08,50681,1369539,54.65
14,INFRATEL,EQ,02-Jun-2017,376.25,376.45,382.90,371.00,373.30,374.65,376.87,1334349,5.028735e+08,37710,496717,37.23
15,INFRATEL,EQ,05-Jun-2017,374.65,381.30,384.90,375.60,380.55,382.45,381.61,3563721,1.359942e+09,74109,1871029,52.50
16,INFRATEL,EQ,06-Jun-2017,382.45,383.00,388.90,379.80,384.70,383.15,384.02,2537956,9.746330e+08,53194,1811141,71.36
17,INFRATEL,EQ,07-Jun-2017,383.15,385.75,388.60,379.70,380.40,383.20,383.79,1610112,6.179385e+08,45025,812548,50.47
18,INFRATEL,EQ,08-Jun-2017,383.20,383.00,383.10,374.80,379.50,379.85,378.44,1107704,4.191941e+08,20214,342689,30.94
19,INFRATEL,EQ,09-Jun-2017,379.85,379.85,384.75,377.10,383.00,382.65,381.29,1545424,5.892548e+08,34955,494657,32.01
20,INFRATEL,EQ,12-Jun-2017,382.65,380.55,386.00,376.80,384.75,384.75,382.05,1660758,6.344843e+08,47895,728996,43.90
21,INFRATEL,EQ,13-Jun-2017,384.75,385.00,389.85,379.55,381.55,384.20,384.56,1863956,7.168024e+08,38488,580484,31.14
22,INFRATEL,EQ,14-Jun-2017,384.20,382.70,387.40,381.45,386.90,386.10,384.75,1317476,5.068970e+08,39782,825288,62.64
23,INFRATEL,EQ,15-Jun-2017,386.10,385.30,389.10,370.65,378.25,374.80,378.94,2369536,8.979236e+08,33682,1201629,50.71
24,INFRATEL,EQ,16-Jun-2017,374.80,374.80,384.65,373.25,375.00,375.10,379.31,2699975,1.024121e+09,53617,1350780,50.03
25,INFRATEL,EQ,19-Jun-2017,375.10,376.00,383.90,373.50,375.05,376.55,380.64,2163886,8.236665e+08,50329,1353450,62.55
26,INFRATEL,EQ,20-Jun-2017,376.55,377.15,381.50,375.70,377.75,377.10,378.48,1331396,5.039095e+08,27127,283356,21.28
27,INFRATEL,EQ,21-Jun-2017,377.10,377.50,378.10,370.50,371.05,371.70,374.03,2388975,8.935386e+08,67053,1379532,57.75
28,INFRATEL,EQ,22-Jun-2017,371.70,372.20,376.50,371.00,374.90,375.00,374.83,1120673,4.200602e+08,40145,595546,53.14
29,INFRATEL,EQ,23-Jun-2017,375.00,377.35,378.55,371.05,372.50,372.15,375.39,2156583,8.095532e+08,61112,981685,45.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,INFRATEL,EQ,27-Mar-2019,312.85,316.90,318.50,311.10,317.00,316.20,315.81,2831679,8.942635e+08,40560,1293283,45.67
465,INFRATEL,EQ,28-Mar-2019,316.20,317.45,319.65,313.45,316.00,317.10,317.08,1752675,5.557310e+08,35195,836330,47.72
466,INFRATEL,EQ,29-Mar-2019,317.10,317.50,319.15,310.85,312.60,313.40,313.64,1743099,5.467129e+08,33996,545051,31.27
467,INFRATEL,EQ,01-Apr-2019,313.40,314.95,317.60,311.50,313.85,314.25,313.85,1556091,4.883735e+08,46984,562431,36.14
468,INFRATEL,EQ,02-Apr-2019,314.25,314.45,318.10,312.15,314.05,315.00,314.97,1660087,5.228746e+08,28684,618101,37.23
469,INFRATEL,EQ,03-Apr-2019,315.00,314.50,320.00,314.15,317.00,317.25,317.10,1971729,6.252407e+08,22026,850460,43.13
470,INFRATEL,EQ,04-Apr-2019,317.25,318.50,319.75,314.70,316.20,316.65,316.76,1339901,4.244321e+08,20584,616134,45.98
471,INFRATEL,EQ,05-Apr-2019,316.65,316.65,320.00,314.40,316.60,316.80,317.07,1034427,3.279891e+08,12743,368035,35.58
472,INFRATEL,EQ,08-Apr-2019,316.80,317.95,318.70,313.70,317.20,316.10,316.36,1035460,3.275760e+08,21364,414562,40.04
473,INFRATEL,EQ,09-Apr-2019,316.10,316.10,318.50,312.50,315.05,315.20,314.88,777799,2.449096e+08,23816,271676,34.93
474,INFRATEL,EQ,10-Apr-2019,315.20,315.10,318.20,313.65,315.75,315.30,316.10,1404102,4.438390e+08,31822,775639,55.24
475,INFRATEL,EQ,11-Apr-2019,315.30,315.35,317.00,311.05,314.00,313.35,314.50,1316742,4.141204e+08,29631,625947,47.54
476,INFRATEL,EQ,12-Apr-2019,313.35,314.00,317.35,313.00,314.45,314.65,315.27,777930,2.452563e+08,29889,327314,42.07
477,INFRATEL,EQ,15-Apr-2019,314.65,314.50,316.50,307.30,309.40,308.45,311.37,1493320,4.649819e+08,26567,498381,33.37
478,INFRATEL,EQ,16-Apr-2019,308.45,310.95,316.90,309.40,312.75,312.95,314.24,2057364,6.465051e+08,44808,660367,32.10
479,INFRATEL,EQ,18-Apr-2019,312.95,312.95,314.45,303.25,306.00,307.20,306.63,2227796,6.831016e+08,27258,578932,25.99
480,INFRATEL,EQ,22-Apr-2019,307.20,306.80,310.85,295.55,299.00,299.60,302.03,1606392,4.851854e+08,22777,337306,21.00
481,INFRATEL,EQ,23-Apr-2019,299.60,301.00,303.65,292.55,298.00,294.00,296.97,1532866,4.552200e+08,28285,341382,22.27
482,INFRATEL,EQ,24-Apr-2019,294.00,297.00,303.50,291.00,301.00,301.50,298.06,2572361,7.667179e+08,37887,781457,30.38
483,INFRATEL,EQ,25-Apr-2019,301.50,287.35,298.00,265.65,272.50,270.70,278.71,24061163,6.706041e+09,180731,6077265,25.26
484,INFRATEL,EQ,26-Apr-2019,270.70,273.00,278.00,271.35,273.00,272.90,274.58,8713787,2.392621e+09,95898,3410481,39.14
485,INFRATEL,EQ,30-Apr-2019,272.90,273.70,278.90,256.50,262.55,262.55,262.97,9291803,2.443455e+09,76896,5170144,55.64
486,INFRATEL,EQ,02-May-2019,262.55,262.55,272.40,262.55,272.00,270.85,270.08,5510874,1.488349e+09,79237,2464269,44.72
487,INFRATEL,EQ,03-May-2019,270.85,272.55,278.55,272.10,273.75,274.00,275.93,4234052,1.168309e+09,61606,1434583,33.88
488,INFRATEL,EQ,06-May-2019,274.00,273.00,273.50,268.30,272.25,271.85,270.47,2351319,6.359665e+08,39964,1048140,44.58
489,INFRATEL,EQ,07-May-2019,271.85,266.90,270.80,265.75,268.00,268.00,267.98,2972102,7.964706e+08,52992,1391563,46.82
490,INFRATEL,EQ,08-May-2019,268.00,268.00,270.30,263.65,267.55,266.70,267.35,2225529,5.949861e+08,51482,1075978,48.35
491,INFRATEL,EQ,09-May-2019,266.70,266.95,269.70,261.50,268.00,267.10,263.92,3520232,9.290673e+08,56601,2051103,58.27
492,INFRATEL,EQ,10-May-2019,267.10,266.30,267.00,260.75,261.75,262.25,262.76,2270319,5.965554e+08,48630,983657,43.33
493,INFRATEL,EQ,13-May-2019,262.25,261.45,269.15,259.60,265.50,265.45,266.46,3369566,8.978471e+08,49631,1103984,32.76

In [192]:
df.shape

(494, 15)

In [193]:
df.head()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,INFRATEL,EQ,15-May-2017,374.70,375.80,375.80,368.65,372.00,371.05,371.08,761032,2.824044e+08,27740,357531,46.98
1,INFRATEL,EQ,16-May-2017,371.05,371.15,380.85,370.05,375.75,376.55,377.05,1346372,5.076459e+08,42924,677288,50.30
2,INFRATEL,EQ,17-May-2017,376.55,377.60,396.50,375.10,388.95,389.90,383.22,2268036,8.691629e+08,83975,1371275,60.46
3,INFRATEL,EQ,18-May-2017,389.90,388.40,388.85,377.00,378.55,378.90,382.60,2014628,7.707910e+08,50270,1025637,50.91
4,INFRATEL,EQ,19-May-2017,378.90,381.10,387.50,374.85,379.40,378.95,379.43,2031322,7.707525e+08,63099,1020560,50.24

In [194]:
df.tail()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
489,INFRATEL,EQ,07-May-2019,271.85,266.90,270.80,265.75,268.00,268.00,267.98,2972102,7.964706e+08,52992,1391563,46.82
490,INFRATEL,EQ,08-May-2019,268.00,268.00,270.30,263.65,267.55,266.70,267.35,2225529,5.949861e+08,51482,1075978,48.35
491,INFRATEL,EQ,09-May-2019,266.70,266.95,269.70,261.50,268.00,267.10,263.92,3520232,9.290673e+08,56601,2051103,58.27
492,INFRATEL,EQ,10-May-2019,267.10,266.30,267.00,260.75,261.75,262.25,262.76,2270319,5.965554e+08,48630,983657,43.33
493,INFRATEL,EQ,13-May-2019,262.25,261.45,269.15,259.60,265.50,265.45,266.46,3369566,8.978471e+08,49631,1103984,32.76

In [195]:
df.describe()

,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
count,494.000000,494.000000,494.000000,494.000000,494.000000,494.000000,494.000000,4.940000e+02,4.940000e+02,494.000000,4.940000e+02,494.000000
mean,330.520749,330.719737,335.645850,325.393623,330.235931,330.299595,330.468158,3.482303e+06,1.177754e+09,57056.591093,2.008089e+06,54.615445
std,51.927489,52.211922,52.848153,51.302441,51.875968,51.971576,52.016754,6.468444e+06,2.533240e+09,31831.065955,4.331648e+06,16.299577
min,249.200000,242.650000,251.700000,242.250000,249.500000,249.200000,249.480000,9.425700e+04,2.497926e+07,1001.000000,3.785800e+04,7.730000
25%,286.862500,287.000000,291.487500,283.450000,286.087500,286.737500,286.465000,1.662104e+06,5.491422e+08,34297.000000,8.341755e+05,43.787500
50%,321.350000,320.900000,324.925000,315.050000,320.500000,320.850000,320.855000,2.481613e+06,8.109989e+08,51504.000000,1.330784e+06,55.235000
75%,375.075000,376.250000,381.262500,371.000000,375.437500,375.075000,376.262500,3.800934e+06,1.276214e+09,70515.750000,2.124545e+06,65.532500
max,479.200000,476.700000,482.800000,467.000000,479.450000,479.200000,476.000000,1.313354e+08,5.259161e+10,197541.000000,8.788042e+07,94.720000

In [196]:
df['Close Price'].min()

249.2

In [197]:
df['Close Price'].max()

479.2

In [198]:
df['Close Price'].mean()

330.29959514170054

In [199]:
df.dtypes

Symbol                     object
Series                     object
Date                       object
Prev Close                float64
Open Price                float64
High Price                float64
Low Price                 float64
Last Price                float64
Close Price               float64
Average Price             float64
Total Traded Quantity       int64
Turnover                  float64
No. of Trades               int64
Deliverable Qty             int64
% Dly Qt to Traded Qty    float64
dtype: object

In [200]:
df['Date'] = df.Date.astype('datetime64')

In [201]:
df.dtypes

Symbol                            object
Series                            object
Date                      datetime64[ns]
Prev Close                       float64
Open Price                       float64
High Price                       float64
Low Price                        float64
Last Price                       float64
Close Price                      float64
Average Price                    float64
Total Traded Quantity              int64
Turnover                         float64
No. of Trades                      int64
Deliverable Qty                    int64
% Dly Qt to Traded Qty           float64
dtype: object

In [202]:
df['Date'].max()-df['Date'].min()

Timedelta('728 days 00:00:00')

In [203]:
df.head()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,INFRATEL,EQ,2017-05-15,374.70,375.80,375.80,368.65,372.00,371.05,371.08,761032,2.824044e+08,27740,357531,46.98
1,INFRATEL,EQ,2017-05-16,371.05,371.15,380.85,370.05,375.75,376.55,377.05,1346372,5.076459e+08,42924,677288,50.30
2,INFRATEL,EQ,2017-05-17,376.55,377.60,396.50,375.10,388.95,389.90,383.22,2268036,8.691629e+08,83975,1371275,60.46
3,INFRATEL,EQ,2017-05-18,389.90,388.40,388.85,377.00,378.55,378.90,382.60,2014628,7.707910e+08,50270,1025637,50.91
4,INFRATEL,EQ,2017-05-19,378.90,381.10,387.50,374.85,379.40,378.95,379.43,2031322,7.707525e+08,63099,1020560,50.24

In [204]:
df.Date.dt.month

0      5
1      5
2      5
3      5
4      5
5      5
6      5
7      5
8      5
9      5
10     5
11     5
12     5
13     6
14     6
15     6
16     6
17     6
18     6
19     6
20     6
21     6
22     6
23     6
24     6
25     6
26     6
27     6
28     6
29     6
      ..
464    3
465    3
466    3
467    4
468    4
469    4
470    4
471    4
472    4
473    4
474    4
475    4
476    4
477    4
478    4
479    4
480    4
481    4
482    4
483    4
484    4
485    4
486    5
487    5
488    5
489    5
490    5
491    5
492    5
493    5
Name: Date, Length: 494, dtype: int64

In [205]:
df['year'] = df['Date'].dt.year

In [206]:
df['month'] = df['Date'].dt.month

In [207]:
# df['VWAP'] = (df['Average Price']*df['Total Traded Quantity'])/(df['Total Traded Quantity'].sum())

In [208]:
# df = df.groupby(['year','month']).sum()

In [209]:
df['Turnover'] = df['Average Price']*df['Total Traded Quantity']

In [210]:
df.rename(columns={'Total Traded Quantity':'Total_Traded_Quantity'}, inplace = True)

In [211]:
VWAP = [] 
VWAP = df.groupby(['year','month']).Turnover.sum() / (df.groupby(['year','month']).Total_Traded_Quantity.sum())

In [212]:
VWAP

year  month
2017  5        375.846561
      6        378.912788
      7        408.763526
      8        387.253628
      9        381.557636
      10       439.959226
      11       399.665669
      12       368.196024
2018  1        356.510027
      2        341.306028
      3        336.320806
      4        331.565382
      5        314.730942
      6        293.296320
      7        293.943174
      8        286.350532
      9        272.271621
      10       263.181141
      11       261.632615
      12       256.777418
2019  1        282.001076
      2        308.647251
      3        315.128644
      4        287.643683
      5        268.676352
dtype: float64

In [213]:
df.head()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total_Traded_Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty,year,month
0,INFRATEL,EQ,2017-05-15,374.70,375.80,375.80,368.65,372.00,371.05,371.08,761032,2.824038e+08,27740,357531,46.98,2017,5
1,INFRATEL,EQ,2017-05-16,371.05,371.15,380.85,370.05,375.75,376.55,377.05,1346372,5.076496e+08,42924,677288,50.30,2017,5
2,INFRATEL,EQ,2017-05-17,376.55,377.60,396.50,375.10,388.95,389.90,383.22,2268036,8.691568e+08,83975,1371275,60.46,2017,5
3,INFRATEL,EQ,2017-05-18,389.90,388.40,388.85,377.00,378.55,378.90,382.60,2014628,7.707967e+08,50270,1025637,50.91,2017,5
4,INFRATEL,EQ,2017-05-19,378.90,381.10,387.50,374.85,379.40,378.95,379.43,2031322,7.707445e+08,63099,1020560,50.24,2017,5

In [214]:
def calc_avg(n):
    ts = pd.to_datetime(n)
    print(df.loc[df.Date>=ts,'Average Price'])

In [215]:
calc_avg('1/1/2018')

159    371.52
160    377.43
161    379.56
162    379.19
163    377.01
164    374.40
165    371.11
166    367.63
167    366.92
168    370.93
169    374.32
170    370.21
171    366.89
172    350.23
173    343.63
174    344.36
175    341.71
176    341.79
177    344.98
178    347.36
179    347.12
180    346.84
181    346.78
182    345.25
183    344.10
184    343.75
185    345.15
186    346.33
187    341.65
188    339.35
        ...
464    315.81
465    317.08
466    313.64
467    313.85
468    314.97
469    317.10
470    316.76
471    317.07
472    316.36
473    314.88
474    316.10
475    314.50
476    315.27
477    311.37
478    314.24
479    306.63
480    302.03
481    296.97
482    298.06
483    278.71
484    274.58
485    262.97
486    270.08
487    275.93
488    270.47
489    267.98
490    267.35
491    263.92
492    262.76
493    266.46
Name: Average Price, Length: 335, dtype: float64

In [216]:
def cal_avg(n):
    d = df.shape[0]-n
    return df.loc[d:,'Average Price']

In [217]:
cal_avg(5)

489    267.98
490    267.35
491    263.92
492    262.76
493    266.46
Name: Average Price, dtype: float64

In [218]:
def cal_average(n):
    start_date = df['Date'].max() - pd.Timedelta(n, unit='D')
    # start_date = pd.to_datetime('today') - pd.Timedelta(n, unit='D')
    return df[df['Date'] >= start_date].loc[:,'Average Price']

In [219]:
# For last N days
cal_average(5)

490    267.35
491    263.92
492    262.76
493    266.46
Name: Average Price, dtype: float64

In [220]:
# For 1 week
cal_average(7)

488    270.47
489    267.98
490    267.35
491    263.92
492    262.76
493    266.46
Name: Average Price, dtype: float64

In [221]:
# For 2 weeks
cal_average(14)

485    262.97
486    270.08
487    275.93
488    270.47
489    267.98
490    267.35
491    263.92
492    262.76
493    266.46
Name: Average Price, dtype: float64

In [222]:
# For 1 month
cal_average(30)

477    311.37
478    314.24
479    306.63
480    302.03
481    296.97
482    298.06
483    278.71
484    274.58
485    262.97
486    270.08
487    275.93
488    270.47
489    267.98
490    267.35
491    263.92
492    262.76
493    266.46
Name: Average Price, dtype: float64

In [223]:
# For 3 months
cal_average(90)

435    314.26
436    305.76
437    296.61
438    303.42
439    316.13
440    320.97
441    317.47
442    309.64
443    316.28
444    305.67
445    305.69
446    300.79
447    294.49
448    295.10
449    294.93
450    303.56
451    306.69
452    306.61
453    316.15
454    316.37
455    314.78
456    315.14
457    313.53
458    316.53
459    327.75
460    327.76
461    319.16
462    308.88
463    310.83
464    315.81
465    317.08
466    313.64
467    313.85
468    314.97
469    317.10
470    316.76
471    317.07
472    316.36
473    314.88
474    316.10
475    314.50
476    315.27
477    311.37
478    314.24
479    306.63
480    302.03
481    296.97
482    298.06
483    278.71
484    274.58
485    262.97
486    270.08
487    275.93
488    270.47
489    267.98
490    267.35
491    263.92
492    262.76
493    266.46
Name: Average Price, dtype: float64

In [224]:
# For 6 months
cal_average(180)

373    259.69
374    257.67
375    259.72
376    259.75
377    259.81
378    259.14
379    255.84
380    262.24
381    264.78
382    260.17
383    261.35
384    257.97
385    256.65
386    254.80
387    257.57
388    255.65
389    253.94
390    249.97
391    251.38
392    251.99
393    249.48
394    250.07
395    252.40
396    254.92
397    261.90
398    261.92
399    257.13
400    263.18
401    261.18
402    265.85
        ...
464    315.81
465    317.08
466    313.64
467    313.85
468    314.97
469    317.10
470    316.76
471    317.07
472    316.36
473    314.88
474    316.10
475    314.50
476    315.27
477    311.37
478    314.24
479    306.63
480    302.03
481    296.97
482    298.06
483    278.71
484    274.58
485    262.97
486    270.08
487    275.93
488    270.47
489    267.98
490    267.35
491    263.92
492    262.76
493    266.46
Name: Average Price, Length: 121, dtype: float64

In [225]:
# For 1 year
cal_average(365)

248    318.85
249    313.18
250    314.75
251    321.05
252    319.17
253    321.12
254    315.85
255    316.94
256    316.44
257    314.17
258    312.98
259    306.11
260    300.98
261    300.03
262    300.32
263    297.04
264    292.84
265    294.54
266    293.85
267    297.33
268    300.14
269    300.11
270    300.31
271    296.61
272    293.16
273    290.68
274    289.10
275    287.17
276    278.43
277    284.11
        ...
464    315.81
465    317.08
466    313.64
467    313.85
468    314.97
469    317.10
470    316.76
471    317.07
472    316.36
473    314.88
474    316.10
475    314.50
476    315.27
477    311.37
478    314.24
479    306.63
480    302.03
481    296.97
482    298.06
483    278.71
484    274.58
485    262.97
486    270.08
487    275.93
488    270.47
489    267.98
490    267.35
491    263.92
492    262.76
493    266.46
Name: Average Price, Length: 246, dtype: float64

In [226]:
def cal_per(n):
    start_date = df['Date'].max() - pd.Timedelta(n, unit='D')
    df1 = df[df['Date'] >= start_date].loc[:,'Close Price']
    df2 = df[df['Date'] >= start_date].loc[:,'Prev Close']
    df1 = df1-df2
    profit = (df1/df2)*100
#     m = profit.shape[0]
#     print(m)
#     while(m>0):
#         m = m-1
#         if profit[m]<0:
#             print('Loss: ',profit)
#         elif profit[m]>0:
#             print('Profit: ',profit)
#         m=m-1
#     print(type(profit))
    print(profit)

In [227]:
# For last N days
cal_per(5)

490   -0.485075
491    0.149981
492   -1.815799
493    1.220210
dtype: float64

In [228]:
# For 1 week
cal_per(7)

488   -0.784672
489   -1.416222
490   -0.485075
491    0.149981
492   -1.815799
493    1.220210
dtype: float64

In [229]:
# For 2 weeks
cal_per(14)

485   -3.792598
486    3.161303
487    1.163005
488   -0.784672
489   -1.416222
490   -0.485075
491    0.149981
492   -1.815799
493    1.220210
dtype: float64

In [230]:
# For 1 month
cal_per(30)

477    -1.970443
478     1.458907
479    -1.837354
480    -2.473958
481    -1.869159
482     2.551020
483   -10.215589
484     0.812708
485    -3.792598
486     3.161303
487     1.163005
488    -0.784672
489    -1.416222
490    -0.485075
491     0.149981
492    -1.815799
493     1.220210
dtype: float64

In [231]:
# For 3 months
cal_per(90)

435    -3.292117
436    -2.732939
437    -2.333224
438     3.263795
439     3.307266
440     0.441571
441    -0.078505
442    -1.775613
443     0.335946
444    -3.077168
445     1.332456
446    -3.652597
447    -1.044650
448    -0.136217
449     0.988917
450     2.161067
451     1.024624
452    -0.049076
453     4.648118
454    -1.047857
455    -1.011538
456     0.383203
457    -0.365834
458     1.564496
459     2.986482
460    -0.778388
461    -2.753423
462    -3.005378
463     2.038487
464     1.070801
465     0.284630
466    -1.166824
467     0.271219
468     0.238663
469     0.714286
470    -0.189125
471     0.047371
472    -0.220960
473    -0.284720
474     0.031726
475    -0.618459
476     0.414872
477    -1.970443
478     1.458907
479    -1.837354
480    -2.473958
481    -1.869159
482     2.551020
483   -10.215589
484     0.812708
485    -3.792598
486     3.161303
487     1.163005
488    -0.784672
489    -1.416222
490    -0.485075
491     0.149981
492    -1.815799
493     1.220210
dtype: float64

In [232]:
# For 6 months
cal_per(180)

373     0.638545
374    -1.788118
375     1.644479
376     0.134823
377     0.134641
378    -0.557050
379    -0.289743
380     1.801627
381     0.532826
382    -1.703578
383     2.233776
384    -3.277453
385    -0.292113
386    -0.449219
387     1.373357
388    -1.045094
389    -1.095247
390    -0.988728
391     1.118434
392    -0.967806
393    -0.598325
394     1.143660
395     1.150565
396    -0.137282
397     3.476041
398    -0.550389
399    -0.820611
400     1.039061
401     0.019044
402     1.599391
         ...
464     1.070801
465     0.284630
466    -1.166824
467     0.271219
468     0.238663
469     0.714286
470    -0.189125
471     0.047371
472    -0.220960
473    -0.284720
474     0.031726
475    -0.618459
476     0.414872
477    -1.970443
478     1.458907
479    -1.837354
480    -2.473958
481    -1.869159
482     2.551020
483   -10.215589
484     0.812708
485    -3.792598
486     3.161303
487     1.163005
488    -0.784672
489    -1.416222
490    -0.485075
491     0.149981
492    -1.815799
493     1.220210
Length: 121, dtype: float64

In [233]:
# For 1 year
cal_per(365)

248    -1.203689
249    -1.123418
250     0.880141
251     2.078046
252    -1.740482
253     1.755496
254    -1.818464
255     0.459079
256     0.330917
257    -1.099419
258    -1.318088
259    -1.866752
260    -1.229911
261    -0.830151
262     0.669680
263    -1.829370
264    -0.169405
265    -0.016969
266    -0.271555
267     1.565691
268     0.536193
269    -0.083333
270     0.250209
271    -1.331115
272    -0.978078
273    -0.783379
274    -1.218675
275    -0.851434
276    -1.997897
277     2.288984
         ...
464     1.070801
465     0.284630
466    -1.166824
467     0.271219
468     0.238663
469     0.714286
470    -0.189125
471     0.047371
472    -0.220960
473    -0.284720
474     0.031726
475    -0.618459
476     0.414872
477    -1.970443
478     1.458907
479    -1.837354
480    -2.473958
481    -1.869159
482     2.551020
483   -10.215589
484     0.812708
485    -3.792598
486     3.161303
487     1.163005
488    -0.784672
489    -1.416222
490    -0.485075
491     0.149981
492    -1.815799
493     1.220210
Length: 246, dtype: float64

In [234]:
df['Day_Perc_Change'] = df['Close Price'].pct_change()*100

In [235]:
df['Day_Perc_Change'].fillna(0, inplace = True)

In [236]:
df.head()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total_Traded_Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty,year,month,Day_Perc_Change
0,INFRATEL,EQ,2017-05-15,374.70,375.80,375.80,368.65,372.00,371.05,371.08,761032,2.824038e+08,27740,357531,46.98,2017,5,0.000000
1,INFRATEL,EQ,2017-05-16,371.05,371.15,380.85,370.05,375.75,376.55,377.05,1346372,5.076496e+08,42924,677288,50.30,2017,5,1.482280
2,INFRATEL,EQ,2017-05-17,376.55,377.60,396.50,375.10,388.95,389.90,383.22,2268036,8.691568e+08,83975,1371275,60.46,2017,5,3.545346
3,INFRATEL,EQ,2017-05-18,389.90,388.40,388.85,377.00,378.55,378.90,382.60,2014628,7.707967e+08,50270,1025637,50.91,2017,5,-2.821236
4,INFRATEL,EQ,2017-05-19,378.90,381.10,387.50,374.85,379.40,378.95,379.43,2031322,7.707445e+08,63099,1020560,50.24,2017,5,0.013196

In [237]:
for ind, row in df.iterrows():
    if -0.5<df.loc[ind, 'Day_Perc_Change']<0.5:
        df.loc[ind, "Trend"] = 'Slight or No change'
    elif 0.5<df.loc[ind,'Day_Perc_Change']<1.0:
        df.loc[ind, "Trend"] = 'Slight Positive'
    elif -1.0<df.loc[ind,'Day_Perc_Change']<-0.5:
        df.loc[ind, "Trend"] = 'Slight negative'
    elif 1<df.loc[ind,'Day_Perc_Change']<3:
        df.loc[ind, "Trend"] = 'Positive'
    elif -3<df.loc[ind,'Day_Perc_Change']<-1:
        df.loc[ind, "Trend"] = 'Negative'
    elif 3<df.loc[ind,'Day_Perc_Change']<7:
        df.loc[ind, "Trend"] = 'Among top gainers'
    elif -7<df.loc[ind,'Day_Perc_Change']<-3:
        df.loc[ind, "Trend"] = 'Among top losers'
    elif df.loc[ind,'Day_Perc_Change']>7:
        df.loc[ind, "Trend"] = 'Bull run'
    elif df.loc[ind,'Day_Perc_Change']<-7:
        df.loc[ind, "Trend"] = 'Bear drop'

In [238]:
df.head(10)

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total_Traded_Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty,year,month,Day_Perc_Change,Trend
0,INFRATEL,EQ,2017-05-15,374.70,375.80,375.80,368.65,372.00,371.05,371.08,761032,2.824038e+08,27740,357531,46.98,2017,5,0.000000,Slight or No change
1,INFRATEL,EQ,2017-05-16,371.05,371.15,380.85,370.05,375.75,376.55,377.05,1346372,5.076496e+08,42924,677288,50.30,2017,5,1.482280,Positive
2,INFRATEL,EQ,2017-05-17,376.55,377.60,396.50,375.10,388.95,389.90,383.22,2268036,8.691568e+08,83975,1371275,60.46,2017,5,3.545346,Among top gainers
3,INFRATEL,EQ,2017-05-18,389.90,388.40,388.85,377.00,378.55,378.90,382.60,2014628,7.707967e+08,50270,1025637,50.91,2017,5,-2.821236,Negative
4,INFRATEL,EQ,2017-05-19,378.90,381.10,387.50,374.85,379.40,378.95,379.43,2031322,7.707445e+08,63099,1020560,50.24,2017,5,0.013196,Slight or No change
5,INFRATEL,EQ,2017-05-22,378.95,383.70,389.30,376.15,388.20,387.95,385.56,2772691,1.069039e+09,73071,1228540,44.31,2017,5,2.374984,Positive
6,INFRATEL,EQ,2017-05-23,387.95,385.00,390.00,378.40,379.90,379.85,382.84,3811223,1.459089e+09,60957,2039492,53.51,2017,5,-2.087898,Negative
7,INFRATEL,EQ,2017-05-24,379.85,379.85,382.00,367.20,368.45,369.00,372.49,3134390,1.167529e+09,83856,1860115,59.35,2017,5,-2.856391,Negative
8,INFRATEL,EQ,2017-05-25,369.00,369.10,376.35,365.85,368.70,373.50,371.80,7287977,2.709670e+09,89929,6053646,83.06,2017,5,1.219512,Positive
9,INFRATEL,EQ,2017-05-26,373.50,370.00,377.20,366.30,369.50,369.95,371.45,1918463,7.126131e+08,43541,788763,41.11,2017,5,-0.950469,Slight negative

In [239]:
df

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total_Traded_Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty,year,month,Day_Perc_Change,Trend
0,INFRATEL,EQ,2017-05-15,374.70,375.80,375.80,368.65,372.00,371.05,371.08,761032,2.824038e+08,27740,357531,46.98,2017,5,0.000000,Slight or No change
1,INFRATEL,EQ,2017-05-16,371.05,371.15,380.85,370.05,375.75,376.55,377.05,1346372,5.076496e+08,42924,677288,50.30,2017,5,1.482280,Positive
2,INFRATEL,EQ,2017-05-17,376.55,377.60,396.50,375.10,388.95,389.90,383.22,2268036,8.691568e+08,83975,1371275,60.46,2017,5,3.545346,Among top gainers
3,INFRATEL,EQ,2017-05-18,389.90,388.40,388.85,377.00,378.55,378.90,382.60,2014628,7.707967e+08,50270,1025637,50.91,2017,5,-2.821236,Negative
4,INFRATEL,EQ,2017-05-19,378.90,381.10,387.50,374.85,379.40,378.95,379.43,2031322,7.707445e+08,63099,1020560,50.24,2017,5,0.013196,Slight or No change
5,INFRATEL,EQ,2017-05-22,378.95,383.70,389.30,376.15,388.20,387.95,385.56,2772691,1.069039e+09,73071,1228540,44.31,2017,5,2.374984,Positive
6,INFRATEL,EQ,2017-05-23,387.95,385.00,390.00,378.40,379.90,379.85,382.84,3811223,1.459089e+09,60957,2039492,53.51,2017,5,-2.087898,Negative
7,INFRATEL,EQ,2017-05-24,379.85,379.85,382.00,367.20,368.45,369.00,372.49,3134390,1.167529e+09,83856,1860115,59.35,2017,5,-2.856391,Negative
8,INFRATEL,EQ,2017-05-25,369.00,369.10,376.35,365.85,368.70,373.50,371.80,7287977,2.709670e+09,89929,6053646,83.06,2017,5,1.219512,Positive
9,INFRATEL,EQ,2017-05-26,373.50,370.00,377.20,366.30,369.50,369.95,371.45,1918463,7.126131e+08,43541,788763,41.11,2017,5,-0.950469,Slight negative
10,INFRATEL,EQ,2017-05-29,369.95,370.00,381.40,367.70,377.10,379.35,376.57,3887542,1.463932e+09,54997,2827505,72.73,2017,5,2.540884,Positive
11,INFRATEL,EQ,2017-05-30,379.35,379.35,379.85,365.65,373.00,372.25,371.46,1273594,4.730892e+08,28694,420437,33.01,2017,5,-1.871623,Negative
12,INFRATEL,EQ,2017-05-31,372.25,374.25,374.35,360.65,368.20,366.60,365.34,3613527,1.320166e+09,132010,2260332,62.55,2017,5,-1.517797,Negative
13,INFRATEL,EQ,2017-06-01,366.60,370.10,379.45,369.80,377.00,376.25,375.07,2505966,9.399127e+08,50681,1369539,54.65,2017,6,2.632297,Positive
14,INFRATEL,EQ,2017-06-02,376.25,376.45,382.90,371.00,373.30,374.65,376.87,1334349,5.028761e+08,37710,496717,37.23,2017,6,-0.425249,Slight or No change
15,INFRATEL,EQ,2017-06-05,374.65,381.30,384.90,375.60,380.55,382.45,381.61,3563721,1.359952e+09,74109,1871029,52.50,2017,6,2.081943,Positive
16,INFRATEL,EQ,2017-06-06,382.45,383.00,388.90,379.80,384.70,383.15,384.02,2537956,9.746259e+08,53194,1811141,71.36,2017,6,0.183030,Slight or No change
17,INFRATEL,EQ,2017-06-07,383.15,385.75,388.60,379.70,380.40,383.20,383.79,1610112,6.179449e+08,45025,812548,50.47,2017,6,0.013050,Slight or No change
18,INFRATEL,EQ,2017-06-08,383.20,383.00,383.10,374.80,379.50,379.85,378.44,1107704,4.191995e+08,20214,342689,30.94,2017,6,-0.874217,Slight negative
19,INFRATEL,EQ,2017-06-09,379.85,379.85,384.75,377.10,383.00,382.65,381.29,1545424,5.892547e+08,34955,494657,32.01,2017,6,0.737133,Slight Positive
20,INFRATEL,EQ,2017-06-12,382.65,380.55,386.00,376.80,384.75,384.75,382.05,1660758,6.344926e+08,47895,728996,43.90,2017,6,0.548804,Slight Positive
21,INFRATEL,EQ,2017-06-13,384.75,385.00,389.85,379.55,381.55,384.20,384.56,1863956,7.168029e+08,38488,580484,31.14,2017,6,-0.142950,Slight or No change
22,INFRATEL,EQ,2017-06-14,384.20,382.70,387.40,381.45,386.90,386.10,384.75,1317476,5.068989e+08,39782,825288,62.64,2017,6,0.494534,Slight or No change
23,INFRATEL,EQ,2017-06-15,386.10,385.30,389.10,370.65,378.25,374.80,378.94,2369536,8.979120e+08,33682,1201629,50.71,2017,6,-2.926703,Negative
24,INFRATEL,EQ,2017-06-16,374.80,374.80,384.65,373.25,375.00,375.10,379.31,2699975,1.024128e+09,53617,1350780,50.03,2017,6,0.080043,Slight or No change
25,INFRATEL,EQ,2017-06-19,375.10,376.00,383.90,373.50,375.05,376.55,380.64,2163886,8.236616e+08,50329,1353450,62.55,2017,6,0.386564,Slight or No change
26,INFRATEL,EQ,2017-06-20,376.55,377.15,381.50,375.70,377.75,377.10,378.48,1331396,5.039068e+08,27127,283356,21.28,2017,6,0.146063,Slight or No change
27,INFRATEL,EQ,2017-06-21,377.10,377.50,378.10,370.50,371.05,371.70,374.03,2388975,8.935483e+08,67053,1379532,57.75,2017,6,-1.431981,Negative
28,INFRATEL,EQ,2017-06-22,371.70,372.20,376.50,371.00,374.90,375.00,374.83,1120673,4.200619e+08,40145,595546,53.14,2017,6,0.887813,Slight Positive
29,INFRATEL,EQ,2017-06-23,375.00,377.35,378.55,371.05,372.50,372.15,375.39,2156583,8.095597e+08,61112,981685,45.52,2017,6,-0.760000,Slight negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,INFRATEL,EQ,2019-03-27,312.85,316.90,318.50,311.10,317.00,316.20,315.81,2831679,8.942725e+08,40560,1293283,45.67,2019,3,1.070801,Positive
465,INFRATEL,EQ,2019-03-28,316.20,317.45,319.65,313.45,316.00,317.10,317.08,1752675,5.557382e+08,35195,836330,47.72,2019,3,0.284630,Slight or No change
466,INFRATEL,EQ,2019-03-29,317.10,317.50,319.15,310.85,312.60,313.40,313.64,1743099,5.467056e+08,33996,545051,31.27,2019,3,-1.166824,Negative
467,INFRATEL,EQ,2019-04-01,313.40,314.95,317.60,311.50,313.85,314.25,313.85,1556091,4.883792e+08,46984,562431,36.14,2019,4,0.271219,Slight or No change
468,INFRATEL,EQ,2019-04-02,314.25,314.45,318.10,312.15,314.05,315.00,314.97,1660087,5.228776e+08,28684,618101,37.23,2019,4,0.238663,Slight or No change
469,INFRATEL,EQ,2019-04-03,315.00,314.50,320.00,314.15,317.00,317.25,317.10,1971729,6.252353e+08,22026,850460,43.13,2019,4,0.714286,Slight Positive
470,INFRATEL,EQ,2019-04-04,317.25,318.50,319.75,314.70,316.20,316.65,316.76,1339901,4.244270e+08,20584,616134,45.98,2019,4,-0.189125,Slight or No change
471,INFRATEL,EQ,2019-04-05,316.65,316.65,320.00,314.40,316.60,316.80,317.07,1034427,3.279858e+08,12743,368035,35.58,2019,4,0.047371,Slight or No change
472,INFRATEL,EQ,2019-04-08,316.80,317.95,318.70,313.70,317.20,316.10,316.36,1035460,3.275781e+08,21364,414562,40.04,2019,4,-0.220960,Slight or No change
473,INFRATEL,EQ,2019-04-09,316.10,316.10,318.50,312.50,315.05,315.20,314.88,777799,2.449133e+08,23816,271676,34.93,2019,4,-0.284720,Slight or No change
474,INFRATEL,EQ,2019-04-10,315.20,315.10,318.20,313.65,315.75,315.30,316.10,1404102,4.438366e+08,31822,775639,55.24,2019,4,0.031726,Slight or No change
475,INFRATEL,EQ,2019-04-11,315.30,315.35,317.00,311.05,314.00,313.35,314.50,1316742,4.141154e+08,29631,625947,47.54,2019,4,-0.618459,Slight negative
476,INFRATEL,EQ,2019-04-12,313.35,314.00,317.35,313.00,314.45,314.65,315.27,777930,2.452580e+08,29889,327314,42.07,2019,4,0.414872,Slight or No change
477,INFRATEL,EQ,2019-04-15,314.65,314.50,316.50,307.30,309.40,308.45,311.37,1493320,4.649750e+08,26567,498381,33.37,2019,4,-1.970443,Negative
478,INFRATEL,EQ,2019-04-16,308.45,310.95,316.90,309.40,312.75,312.95,314.24,2057364,6.465061e+08,44808,660367,32.10,2019,4,1.458907,Positive
479,INFRATEL,EQ,2019-04-18,312.95,312.95,314.45,303.25,306.00,307.20,306.63,2227796,6.831091e+08,27258,578932,25.99,2019,4,-1.837354,Negative
480,INFRATEL,EQ,2019-04-22,307.20,306.80,310.85,295.55,299.00,299.60,302.03,1606392,4.851786e+08,22777,337306,21.00,2019,4,-2.473958,Negative
481,INFRATEL,EQ,2019-04-23,299.60,301.00,303.65,292.55,298.00,294.00,296.97,1532866,4.552152e+08,28285,341382,22.27,2019,4,-1.869159,Negative
482,INFRATEL,EQ,2019-04-24,294.00,297.00,303.50,291.00,301.00,301.50,298.06,2572361,7.667179e+08,37887,781457,30.38,2019,4,2.551020,Positive
483,INFRATEL,EQ,2019-04-25,301.50,287.35,298.00,265.65,272.50,270.70,278.71,24061163,6.706087e+09,180731,6077265,25.26,2019,4,-10.215589,Bear drop
484,INFRATEL,EQ,2019-04-26,270.70,273.00,278.00,271.35,273.00,272.90,274.58,8713787,2.392632e+09,95898,3410481,39.14,2019,4,0.812708,Slight Positive
485,INFRATEL,EQ,2019-04-30,272.90,273.70,278.90,256.50,262.55,262.55,262.97,9291803,2.443465e+09,76896,5170144,55.64,2019,4,-3.792598,Among top losers
486,INFRATEL,EQ,2019-05-02,262.55,262.55,272.40,262.55,272.00,270.85,270.08,5510874,1.488377e+09,79237,2464269,44.72,2019,5,3.161303,Among top gainers
487,INFRATEL,EQ,2019-05-03,270.85,272.55,278.55,272.10,273.75,274.00,275.93,4234052,1.168302e+09,61606,1434583,33.88,2019,5,1.163005,Positive
488,INFRATEL,EQ,2019-05-06,274.00,273.00,273.50,268.30,272.25,271.85,270.47,2351319,6.359612e+08,39964,1048140,44.58,2019,5,-0.784672,Slight negative
489,INFRATEL,EQ,2019-05-07,271.85,266.90,270.80,265.75,268.00,268.00,267.98,2972102,7.964639e+08,52992,1391563,46.82,2019,5,-1.416222,Negative
490,INFRATEL,EQ,2019-05-08,268.00,268.00,270.30,263.65,267.55,266.70,267.35,2225529,5.949952e+08,51482,1075978,48.35,2019,5,-0.485075,Slight or No change
491,INFRATEL,EQ,2019-05-09,266.70,266.95,269.70,261.50,268.00,267.10,263.92,3520232,9.290596e+08,56601,2051103,58.27,2019,5,0.149981,Slight or No change
492,INFRATEL,EQ,2019-05-10,267.10,266.30,267.00,260.75,261.75,262.25,262.76,2270319,5.965490e+08,48630,983657,43.33,2019,5,-1.815799,Negative
493,INFRATEL,EQ,2019-05-13,262.25,261.45,269.15,259.60,265.50,265.45,266.46,3369566,8.978546e+08,49631,1103984,32.76,2019,5,1.220210,Positive

In [240]:
df.groupby(['Trend']).Total_Traded_Quantity.mean()

Trend
Among top gainers      5.816889e+06
Among top losers       1.015391e+07
Bear drop              1.429408e+07
Negative               2.684517e+06
Positive               3.333011e+06
Slight Positive        3.557961e+06
Slight negative        2.884543e+06
Slight or No change    2.744105e+06
Name: Total_Traded_Quantity, dtype: float64

In [241]:
df.groupby(['Trend']).Total_Traded_Quantity.median()

Trend
Among top gainers       4709712.5
Among top losers        3435092.5
Bear drop              14294085.0
Negative                2286066.5
Positive                2802185.0
Slight Positive         2287491.5
Slight negative         2317378.0
Slight or No change     2193471.5
Name: Total_Traded_Quantity, dtype: float64

In [242]:
df.to_csv('../aspiration.ai/week2.csv')